name: Build 

# Trigger this action on pull requests targeting the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # specify the node version you're using (adjust as needed)
    
    # Install dependencies
    - name: Install dependencies
      run: npm install
    
    # Build the Next.js project
    - name: Build Next.js app
      run: npm run build
    
    # Run tests (optional, but recommended)
    - name: Run tests
      run: npm test

    # Optionally you can cache dependencies to speed up the pipeline
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
